# Downstream workflow
on:
  merge_group:
  push:
    branches-ignore:
    # temporary GH branches relating to merge queues (jaraco/skeleton#93)
    - gh-readonly-queue/**
    tags:
    # required if branches-ignore is supplied (jaraco/skeleton#103)
    - '**'
  pull_request:

jobs:
  main:
    uses: coherent-oss/system/.github/workflows/main.yml@main
    permissions:
      contents: write
    secrets:
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
